In [1]:
import pandas as pd
import numpy as np
import DBCV
from dtaidistance import dtw
from dtaidistance import ed
from btseg.clustering.hdbscan_clustering import HDBSCANClusterer

In [3]:
df = pd.read_csv('time_series_1.csv')
df.head()

id                                               path  \
0   1  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   
1   2  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   
2   3  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   
3   4  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   
4   5  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   

                                          slice_path         a_0         a_1  \
0  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...  109.041277  113.159180   
1  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   62.072538   64.195015   
2  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   91.049437   90.088845   
3  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...    3.000000    3.000000   
4  C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...   39.115214   39.204592   

          a_2         a_3         a_4         a_5         a_6  ...      a_350  \
0  113.282832  108.558740  106.794195  105.076163  103.406963  ...  72.532751   
1   65.375837   66.483081   66.753277   67.082039   67.468511  ...  66.490601   
2   89.202018   89.274856   88.459030   87.572827   87.692645  ...  92.655275   
3    3.000000    3.000000    7.211103    7.211103    7.211103  ...   3.000000   
4   39.319207   39.458839   39.623226   39.812058   40.024992  ...  41.593269   

        a_351      a_352      a_353      a_354       a_355       a_356  \
0  102.420701  99.984999  99.724621  99.503769  100.319490  102.176318   
1   66.098411  61.660360  60.530984  60.299254   60.207973   60.074953   
2   92.541882  92.347171  92.265920  92.135769   92.086915   92.048900   
3    3.000000   3.000000   3.000000   3.000000    3.000000    3.000000   
4   41.593269  40.311289  40.199502  39.115214   39.051248   39.012818   

        a_357       a_358       a_359  
0  104.076895  107.004673  107.004673  
1   60.033324   60.000000   61.032778  
2   92.005435   92.005435   92.021737  
3    3.000000    3.000000    3.000000  
4   39.000000   39.012818   39.051248  

[5 rows x 363 columns]

In [7]:
X = df.drop(['id', 'path', 'slice_path'], axis=1).values
len(X)

150

In [8]:
hdbscan = HDBSCANClusterer(min_cluster_samples=5, min_samples=3, metric='dtw')
hdbscan.model

HDBSCAN(cluster_selection_method='leaf', metric='precomputed', min_samples=3)

In [9]:
hdbscan.fit(X)

In [11]:
proba = hdbscan.model.probabilities_
proba

array([0.        , 0.        , 0.        , 1.        , 0.77897737,
       0.        , 0.        , 0.82520005, 1.        , 1.        ,
       1.        , 0.67514087, 0.96738398, 0.        , 1.        ,
       0.        , 1.        , 0.74385335, 0.        , 0.86149483,
       0.77095744, 0.76685987, 0.        , 0.        , 0.91139363,
       0.        , 0.53081882, 0.86859683, 0.79601572, 0.        ,
       0.82741427, 0.91139363, 0.        , 0.        , 0.        ,
       0.91209869, 0.69911481, 0.        , 0.        , 0.55067713,
       0.        , 0.        , 0.        , 1.        , 0.77809809,
       1.        , 1.        , 0.77996932, 0.        , 0.        ,
       0.87712428, 0.        , 0.        , 0.7803739 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.7924717 ,
       0.85125606, 0.        , 0.84669231, 0.        , 0.69530179,
       0.        , 0.66442716, 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.     

In [12]:
out_labels = hdbscan.model.labels_
out_labels

array([-1, -1, -1,  2,  1, -1, -1,  1,  0,  1,  1,  2,  2, -1,  1, -1,  0,
        1, -1,  0,  1,  1, -1, -1,  1, -1,  2,  0,  0, -1,  1,  1, -1, -1,
       -1,  2,  1, -1, -1,  2, -1, -1, -1,  2,  1,  0,  0,  1, -1, -1,  0,
       -1, -1,  0, -1, -1, -1, -1, -1,  2,  1, -1,  1, -1,  1, -1,  2, -1,
       -1, -1,  1, -1, -1, -1, -1,  1, -1,  0,  0, -1, -1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1,  1,  2, -1, -1,  0, -1,  1, -1, -1, -1,  1,
       -1,  2, -1,  0,  1,  1,  0,  1, -1,  1, -1,  0,  1, -1,  2,  1, -1,
       -1,  1, -1, -1,  2, -1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1,
        1, -1, -1, -1,  2, -1,  0,  1, -1,  1, -1,  0, -1, -1],
      dtype=int64)

In [13]:
np.unique(out_labels, return_counts=True)

(array([-1,  0,  1,  2], dtype=int64), array([81, 17, 38, 14], dtype=int64))

In [16]:
result_df = pd.DataFrame({
    'id': list(range(len(X))),
    'group': out_labels,
    'proba': hdbscan.model.probabilities_
})
result_df

id  group     proba
0      0     -1  0.000000
1      1     -1  0.000000
2      2     -1  0.000000
3      3      2  1.000000
4      4      1  0.778977
..   ...    ...       ...
145  145      1  0.827414
146  146     -1  0.000000
147  147      0  0.789219
148  148     -1  0.000000
149  149     -1  0.000000

[150 rows x 3 columns]

In [17]:
result_df.to_csv('result_1.csv')